######################################################################
# Automatically generated by qmake (3.0) ?? ?? 13 17:26:44 2014
######################################################################

TEMPLATE = app
TARGET = Tree
INCLUDEPATH += . \
               ./Trees

QT += widgets
			   
# Input

HEADERS += *.h \
           ./Trees/*.h \
           ./Views/*.h

SOURCES += *.cpp \
           ./Trees/*.cpp \
           ./Views/*.cpp
