######################################################################
# Automatically generated by qmake (3.0) ?? ?? 13 17:26:44 2014
######################################################################

TEMPLATE = app
TARGET = Tree
INCLUDEPATH += .

# Input
SOURCES += main.cpp
